#!/usr/bin/env python3
"""Write the MCF3M M4-L1 qualified pool against documented coverage gaps."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from question_pool import (  # noqa: E402
    coverage_report,
    near_duplicates,
    pool_path,
    prompt_hash,
    rebuild_index,
    validate_pool,
)
from student_authoring import dump_json  # noqa: E402

LESSON = "M4-L1-vertex-form"
SCOPE = (
    "A2.7 and the vertex-form share of A2.10. Completing the square, the quadratic "
    "formula, discriminant, regression, and the full applications lesson stay out of scope."
)


def item(
    *,
    cid: str,
    title: str,
    student_facing: str,
    family_id: str,
    bloom: str,
    rationale: str,
    knowledge: str,
    task_family: str,
    solution: str = "",
    verified_by: str = "",
    role: str = "practice",
    status: str = "accepted",
    recipe: str | None = None,
    variant_of: str | None = None,
    bloom_secondary: str | None = None,
    difficulty: str = "developing",
    minutes: float = 4,
    prereq: list[str] | None = None,
    rin: list[str] | None = None,
    rout: list[str] | None = None,
    codes: list[str] | None = None,
    processes: list[str] | None = None,
    origin: str = "original",
    source_id: str | None = None,
    answer_kind: str = "authored",
    exclusion: str | None = None,
    export: bool = True,
    concepts: list[str] | None = None,
    evidence: list[str] | None = None,
    strategies: list[str] | None = None,
) -> dict:
    """Build one pool record and stamp the prompt hash."""
    rec = {
        "id": cid,
        "status": status,
        "title": title,
        "student_facing": student_facing,
        "role": role,
        "family_id": family_id,
        "variant_of": variant_of,
        "expansion_recipe": recipe,
        "bloom": {"primary": bloom, "secondary": bloom_secondary, "rationale": rationale},
        "knowledge": knowledge,
        "difficulty": {
            "level": difficulty,
            "prerequisites": prereq or ["vertex-form-notation"],
            "est_minutes": minutes,
        },
        "task_family": task_family,
        "representations": {"input": rin or ["symbolic"], "output": rout or ["symbolic"]},
        "structure": {
            "concept_ids": concepts or ["vertex-form"],
            "relationships": [],
            "constraints": [],
            "solution_strategies": strategies or [],
            "expected_evidence": evidence or ["named features or a justified claim"],
        },
        "alignment": {
            "expectation_codes": codes or ["A2.10"],
            "process_ids": processes or ["inspect-vertex-form"],
            "in_scope": status == "accepted",
        },
        "verification": {
            "answer_kind": answer_kind if status == "accepted" else "none",
            "authored_solution": solution if status == "accepted" else None,
            "source_key": None,
            "verified": status == "accepted",
            "verified_by": verified_by if status == "accepted" else None,
            "notes": exclusion,
        },
        "lineage": {
            "origin": origin,
            "source_id": source_id,
            "source_page": None,
            "source_region": None,
            "parent_id": variant_of,
            "prompt_hash": prompt_hash(student_facing),
            "review_version": 1,
        },
        "exclusion_reason": exclusion,
        "student_export": export and status == "accepted",
    }
    return rec


def build() -> dict:
    """Return the M4-L1 pool document."""
    candidates = [
        item(
            cid="vf-read-plus-inside",
            title="Name the vertex when the brackets show a plus",
            student_facing="Consider f(x) = (x + 3)^2 + 1. Name the vertex and the axis of symmetry. Do not sketch yet.",
            family_id="read-vertex-features",
            bloom="apply",
            rationale="Students match the given equation to a(x − h)^2 + k and report (h, k).",
            knowledge="conceptual",
            task_family="interpret",
            solution="Match (x + 3) to (x − h), so h = −3. k = 1. Vertex (−3, 1). Axis x = −3. a = 1 > 0 so a minimum.",
            verified_by="match-to-vertex-form",
            role="diagnostic",
            difficulty="entry",
            minutes=3,
            evidence=["vertex (−3, 1)", "axis x = −3"],
            strategies=["rewrite x + 3 as x − (−3)"],
        ),
        item(
            cid="vf-read-open-down",
            title="Vertex and maximum from a negative a",
            student_facing="Consider y = −3(x + 2)^2 + 4. Name the vertex. Is the vertex a maximum or a minimum? How did you know?",
            family_id="read-vertex-features",
            bloom="apply",
            rationale="Reading (h, k) and using the sign of a, not the sign of k.",
            knowledge="conceptual",
            task_family="interpret",
            solution="h = −2, k = 4. Vertex (−2, 4). a = −3 < 0 so the parabola opens downward: the vertex is a maximum.",
            verified_by="match-to-vertex-form",
            role="guided_example",
            origin="openstax",
            source_id="openstax-ca2e-m51274-vertex-form-definition",
            codes=["A2.10"],
        ),
        item(
            cid="vf-k-zero-maximum",
            title="Maximum when k is zero",
            student_facing="Consider h(x) = −2(x + 1)^2. Where is the vertex? Does this graph have a maximum or a minimum? Could you decide that from k alone?",
            family_id="read-vertex-features",
            bloom="understand",
            bloom_secondary="apply",
            rationale="k = 0, so maximum versus minimum cannot be read from k; it comes from a.",
            knowledge="conceptual",
            task_family="interpret",
            solution="h = −1, k = 0. Vertex (−1, 0). a = −2 < 0, so a maximum. k alone does not decide max vs min.",
            verified_by="match-to-vertex-form",
            role="guided_example",
            origin="ministry-sample",
            source_id="A2.6-example-0",
            codes=["A2.10"],
            difficulty="entry",
        ),
        item(
            cid="vf-expand-half",
            title="Expand ½(x + 2)^2 − 3",
            student_facing="Rewrite g(x) = (1/2)(x + 2)^2 − 3 in standard form, meaning g(x) = ax^2 + bx + c. Then check two x-values in both forms.",
            family_id="equivalent-forms",
            bloom="apply",
            rationale="Carry out expansion; checking values corroborates but does not prove identity.",
            knowledge="procedural",
            task_family="compute",
            solution="(x + 2)^2 = x^2 + 4x + 4. Multiply by 1/2: (1/2)x^2 + 2x + 2. Add −3: (1/2)x^2 + 2x − 1. At x = −2 both give −3; at x = 0 both give −1.",
            verified_by="expand-a-h-k: a=1/2, h=-2, k=-3 → (1/2, 2, -1)",
            role="guided_example",
            origin="openstax",
            source_id="openstax-ca2e-m51274-vertex-form-definition",
            codes=["A2.7"],
            processes=["expand-and-verify"],
            rin=["symbolic"],
            rout=["symbolic", "table"],
        ),
        item(
            cid="vf-ministry-expand",
            title="Ministry sample: expand 3(x − 1)^2 + 4",
            student_facing="Given the vertex form f(x) = 3(x − 1)^2 + 4, express the equation in standard form. Use technology to compare the graphs of these two forms of the equation.",
            family_id="equivalent-forms",
            bloom="apply",
            rationale="Ministry sample for A2.7: expand and compare graphs.",
            knowledge="procedural",
            task_family="compute",
            solution="Authored expansion (not a Ministry key): 3(x^2 − 2x + 1) + 4 = 3x^2 − 6x + 3 + 4 = 3x^2 − 6x + 7. Graphs of both writings coincide.",
            verified_by="expand-a-h-k: a=3, h=1, k=4 → (3, -6, 7)",
            role="practice",
            origin="ministry-sample",
            source_id="ontario-seed-mcf3m-A2.7-sample",
            answer_kind="authored",
            codes=["A2.7"],
            processes=["expand-and-verify"],
        ),
        item(
            cid="vf-form-advantage",
            title="What vertex form makes readable",
            student_facing="Consider f(x) = a(x − h)^2 + k. What can you read from vertex form that is harder to see when the same function is written in standard form f(x) = ax^2 + bx + c? Do not rewrite the function.",
            family_id="form-affordances",
            bloom="understand",
            rationale="Identify the affordance of vertex form without producing another form.",
            knowledge="conceptual",
            task_family="interpret",
            solution="Vertex (h, k), axis x = h, and maximum versus minimum from the sign of a. Standard form makes the y-intercept c easy to see; zeros are not obvious in either of those two writings unless they happen to sit on an axis.",
            verified_by="curriculum-A2.10-share",
            origin="openstax",
            source_id="openstax-ca2e-m51274-advantage-verbal",
            processes=["three-form-contrast"],
        ),
        item(
            cid="vf-range-from-vertex",
            title="Domain and range from vertex form",
            student_facing="Determine the domain and range of f(x) = −2(x + 3)^2 − 6.",
            family_id="read-vertex-features",
            bloom="apply",
            rationale="Range follows from k and the sign of a after the vertex is named.",
            knowledge="conceptual",
            task_family="interpret",
            solution="Vertex (−3, −6), opens downward. Domain: all real x. Range: y ≤ −6.",
            verified_by="vertex-and-opening",
            origin="openstax",
            source_id="m51274-ex-22-authored",
            difficulty="developing",
        ),
        item(
            cid="vf-table-not-proof",
            title="Why matching table values do not prove identity",
            student_facing="Two writings give the same three table values. A student says that proves the writings are the same function for every x. Prove, qualify, or refute that claim.",
            family_id="equivalent-forms",
            bloom="evaluate",
            rationale="A finite table corroborates but does not prove algebraic identity.",
            knowledge="metacognitive",
            task_family="justify",
            recipe="claim-testing",
            role="transfer",
            difficulty="extension",
            minutes=6,
            rin=["table", "symbolic"],
            rout=["verbal"],
            solution="Refute as a proof: finitely many matching outputs cannot guarantee agreement for all real x. Algebraic expansion (or an identity argument) is what proves the writings are the same function. The table is supporting evidence only.",
            verified_by="editorial-math-flag",
            codes=["A2.7"],
            processes=["expand-and-verify"],
            evidence=["qualified claim: table corroborates, expansion proves"],
        ),
        item(
            cid="vf-error-h-sign",
            title="First invalid step: reading +3 as h = 3",
            student_facing="A student writes: “f(x) = (x + 3)^2 + 1, so h = 3, vertex (3, 1).” Locate the first invalid step, explain what went wrong, and repair it.",
            family_id="error-diagnosis",
            bloom="analyze",
            rationale="The work to do is locate and repair the mismatch with (x − h).",
            knowledge="conceptual",
            task_family="diagnose",
            recipe="error-diagnosis",
            role="practice",
            rin=["symbolic", "verbal"],
            rout=["verbal", "symbolic"],
            solution="Invalid at “h = 3”. Vertex form uses (x − h), so x + 3 = x − (−3) and h = −3. The vertex is (−3, 1).",
            verified_by="match-to-vertex-form",
            evidence=["first invalid clause identified", "repaired vertex"],
        ),
        item(
            cid="vf-error-max-from-k",
            title="First invalid step: maximum from the sign of k",
            student_facing="A student writes: “y = −2(x + 1)^2 has k = 0, so it is not a maximum or a minimum.” Locate the first invalid step, explain it, and repair it.",
            family_id="error-diagnosis",
            bloom="analyze",
            rationale="Diagnose using k instead of a for max/min.",
            knowledge="conceptual",
            task_family="diagnose",
            recipe="error-diagnosis",
            solution="Invalid at the claim that k = 0 means there is no max/min. a = −2 < 0, so the graph opens down: the vertex (−1, 0) is a maximum (the maximum value is 0).",
            verified_by="sign-of-a",
        ),
        item(
            cid="vf-error-expand-distribute",
            title="First invalid step in an expansion",
            student_facing="A student expands 2(x + 3)^2 + 1 as 2x^2 + 3^2 + 1 = 2x^2 + 10. Locate the first invalid step, explain it, and repair the expansion.",
            family_id="error-diagnosis",
            bloom="analyze",
            rationale="The binomial must be squared before distributing a.",
            knowledge="procedural",
            task_family="diagnose",
            recipe="error-diagnosis",
            codes=["A2.7"],
            processes=["expand-and-verify"],
            solution="Invalid at replacing (x + 3)^2 by 3^2. Square the binomial: x^2 + 6x + 9. Then distribute 2: 2x^2 + 12x + 18. Add 1: 2x^2 + 12x + 19.",
            verified_by="expand-a-h-k: a=2, h=-3, k=1 → (2, 12, 19)",
        ),
        item(
            cid="vf-method-equivalence",
            title="Choose how to check that two writings are the same curve",
            student_facing="You have f(x) = 2(x + 3)^2 + 1 and a candidate standard form. You may expand algebraically or compare graphs. Using the criterion “prove they are the same function for every x,” which method would you choose, and why?",
            family_id="method-choice",
            bloom="evaluate",
            rationale="Select among valid methods using a stated criterion (prove for all x).",
            knowledge="metacognitive",
            task_family="justify",
            recipe="method-choice",
            role="transfer",
            codes=["A2.7"],
            processes=["expand-and-verify"],
            solution="Choose algebraic expansion (or an equivalent identity). Graphing technology in a window, or a finite table, can corroborate but does not prove agreement for every x. After expanding to 2x^2 + 12x + 19, a graph check is a useful confirmation.",
            verified_by="editorial-math-flag",
        ),
        item(
            cid="vf-zeros-inverse",
            title="Zeros from vertex form by inverse operations",
            student_facing="The graph of f(x) = (x − 1)^2 − 9 meets the x-axis where f(x) = 0. Determine those zeros by inverse operations. You may check on a graph afterward.",
            family_id="zeros-from-vertex-form",
            bloom="apply",
            rationale="Set the vertex form equal to zero and undo the operations; no quadratic formula.",
            knowledge="procedural",
            task_family="compute",
            codes=["A2.10"],
            rin=["symbolic"],
            rout=["symbolic"],
            solution="(x − 1)^2 − 9 = 0 → (x − 1)^2 = 9 → x − 1 = 3 or x − 1 = −3 → x = 4 or x = −2. The zeros are −2 and 4; the x-intercepts are (−2, 0) and (4, 0). Square root notation names the principal (non-negative) root; the ± comes from solving u^2 = 9.",
            verified_by="inverse-operations",
            strategies=["isolate the square", "remember both signs"],
        ),
        item(
            cid="vf-zeros-method-choice",
            title="Choose a method for zeros of a vertex-form equation",
            student_facing="You need the zeros of f(x) = (x − 1)^2 − 9. Inverse operations, a graph, and factoring after expanding are all available. Using the criterion “exact values with the least extra algebra,” which method would you choose, and why?",
            family_id="zeros-from-vertex-form",
            bloom="evaluate",
            rationale="Choose among valid methods with a stated efficiency/reliability criterion.",
            knowledge="metacognitive",
            task_family="justify",
            recipe="method-choice",
            role="transfer",
            variant_of=None,
            solution="Inverse operations on the vertex form: the square is already isolated after adding 9. Expanding first then factoring works but adds algebra. A graph can suggest −2 and 4 but may not certify exactness.",
            verified_by="method-criterion",
        ),
        item(
            cid="vf-vertex-and-point",
            title="Recover a from a vertex and another point",
            student_facing="A parabola has vertex (1, −2) and passes through (3, 2). Determine the vertex-form equation. Is this equation unique given those two conditions?",
            family_id="vertex-and-point-to-function",
            bloom="create",
            rationale="Construct a(x − h)^2 + k from constraints and address uniqueness.",
            knowledge="procedural",
            task_family="construct",
            recipe="constraint-construction",
            role="practice",
            difficulty="extension",
            minutes=6,
            rin=["coordinates"],
            rout=["symbolic"],
            solution="h = 1, k = −2. Plug in (3, 2): a(3 − 1)^2 − 2 = 2 → 4a = 4 → a = 1. So f(x) = (x − 1)^2 − 2. Unique among vertex-form quadratics: a is determined once x ≠ h.",
            verified_by="substitute-second-point",
        ),
        item(
            cid="vf-insufficient-vertex-only",
            title="What remains free if you only know the vertex",
            student_facing="You know a quadratic in vertex form has vertex (2, 5). Is the function uniquely determined? If not, what still needs to be chosen, and what stays the same?",
            family_id="vertex-and-point-to-function",
            bloom="analyze",
            rationale="Identify remaining degrees of freedom (a) when only (h, k) is known.",
            knowledge="conceptual",
            task_family="investigate",
            recipe="constraint-construction",
            role="transfer",
            rin=["coordinates"],
            rout=["verbal"],
            solution="Not unique. h = 2 and k = 5 are fixed, so the axis x = 2 and the turning point stay put. a is still free (except a ≠ 0): different stretches and a possible reflection. One more non-vertex point, or a stated value of a, would determine the function.",
            verified_by="degrees-of-freedom",
        ),
        item(
            cid="vf-construct-same-vertex-different-a",
            title="Two vertex forms with the same turning point",
            student_facing="Construct two different vertex-form equations that both have vertex (0, 3). What is the same on both graphs, and what changes?",
            family_id="constraint-construction",
            bloom="create",
            rationale="Create examples meeting a constraint and compare.",
            knowledge="conceptual",
            task_family="construct",
            recipe="constraint-construction",
            rin=["coordinates"],
            rout=["symbolic", "graph"],
            solution="Any a ≠ 0 works: for example f(x) = (x − 0)^2 + 3 = x^2 + 3 and g(x) = −2x^2 + 3. Both have vertex (0, 3) and axis x = 0. Opening and steepness change with a.",
            verified_by="same-h-k-different-a",
        ),
        item(
            cid="vf-bridge-graph-equation",
            title="Map a labelled graph to vertex form",
            student_facing="A graph of a parabola is labelled with vertex (−4, 1) and one other point (0, −3), and it opens downward. Write a vertex-form equation that fits those features. Name which graph facts became a, h, and k.",
            family_id="representation-bridge",
            bloom="analyze",
            rationale="Map corresponding features across a graph and vertex form.",
            knowledge="conceptual",
            task_family="interpret",
            recipe="representation-bridge",
            rin=["graph", "coordinates"],
            rout=["symbolic"],
            solution="h = −4, k = 1. Opens down so a < 0. Using (0, −3): a(0 + 4)^2 + 1 = −3 → 16a = −4 → a = −1/4. f(x) = −(1/4)(x + 4)^2 + 1.",
            verified_by="substitute-second-point",
        ),
        item(
            cid="vf-bridge-features-table",
            title="Match vertex-form features to a table",
            student_facing="A table of f shows a highest output of 5 at x = −1, and the y-values fall as x moves away from −1 on both sides. Which vertex-form facts does that force, and which fact is still free?",
            family_id="representation-bridge",
            bloom="analyze",
            rationale="Translate table symmetry and an extremum into (h, k) and the sign of a.",
            knowledge="conceptual",
            task_family="interpret",
            recipe="representation-bridge",
            rin=["table"],
            rout=["symbolic", "verbal"],
            solution="Vertex (−1, 5), so h = −1, k = 5. Highest output means a < 0. |a| is not determined by those table facts alone.",
            verified_by="table-extremum",
        ),
        item(
            cid="vf-claim-axis-is-y",
            title="Test the claim that the axis is y = h",
            student_facing="A student says: “For f(x) = 2(x − 4)^2 + 1 the axis of symmetry is y = 4.” Prove, qualify, or refute the claim.",
            family_id="claim-testing",
            bloom="evaluate",
            rationale="Refute a switched coordinate for the axis.",
            knowledge="conceptual",
            task_family="justify",
            recipe="claim-testing",
            solution="Refute. The axis is the vertical line through the vertex: x = h = 4, not y = 4. y = 4 would be a horizontal line through the vertex height k = 1 only if k were 4; here k = 1, and that line is not the axis.",
            verified_by="axis-is-x-equals-h",
        ),
        item(
            cid="vf-form-choice-defend",
            title="Defend a form for a stated decision",
            student_facing="You need the highest point of a quadratic path, not the x-intercepts. Which of standard form, vertex form, or factored form would you choose, and why? Mention what that form does not make obvious.",
            family_id="form-affordances",
            bloom="evaluate",
            rationale="Select and defend the most informative form for a stated decision.",
            knowledge="conceptual",
            task_family="justify",
            recipe="method-choice",
            role="transfer",
            processes=["three-form-contrast"],
            rin=["verbal"],
            rout=["verbal"],
            solution="Choose vertex form: the vertex (h, k) is the high or low point and the sign of a tells which. Factored form makes zeros obvious, not the vertex. Standard form makes the y-intercept obvious; the vertex needs more work (not asked here).",
            verified_by="A2.10-share",
        ),
        item(
            cid="vf-model-arc-domain",
            title="Meaningful domain of a rising-then-falling model",
            student_facing="A water stream is modelled by h(x) = −0.5(x − 2)^2 + 4 for horizontal distance x in metres and height h in metres. The nozzle is at x = 0 and the water lands at h = 0. Determine the vertex. Then state a meaningful domain for this model and say where the equation should not be trusted as a description of the stream.",
            family_id="model-critique",
            bloom="evaluate",
            rationale="Interpret vertex features, then judge domain and limits of the model. Not a full applications lesson and not a physical bungee model.",
            knowledge="conceptual",
            task_family="model",
            recipe="model-critique",
            role="transfer",
            difficulty="extension",
            minutes=7,
            rin=["context", "symbolic"],
            rout=["symbolic", "verbal"],
            codes=["A2.10"],
            solution="Vertex (2, 4): highest point 4 m when x = 2. h(x) = 0 → −0.5(x − 2)^2 + 4 = 0 → (x − 2)^2 = 8 → x = 2 ± √8 = 2 ± 2√2. The landing in front of the nozzle is x = 2 + 2√2 ≈ 4.83 m (x = 2 − 2√2 is behind the nozzle if x = 0 is the nozzle). A meaningful domain is from the nozzle to the landing, about 0 ≤ x ≤ 2 + 2√2. Outside that interval the quadratic is not a model of this stream.",
            verified_by="vertex-and-zeros-then-domain",
        ),
        item(
            cid="vf-maximum-from-vertex-form",
            title="Read a maximum without completing the square",
            student_facing="A ball’s height in metres is modelled by h(t) = −4.9(t − 1.2)^2 + 8 on the flight interval. What is the maximum height, and when does it occur? What in the equation told you?",
            family_id="maximum-from-representations",
            bloom="apply",
            rationale="The maximum is k when a < 0; no completing-the-square.",
            knowledge="conceptual",
            task_family="interpret",
            rin=["context", "symbolic"],
            rout=["symbolic"],
            solution="a = −4.9 < 0 so the vertex is a maximum. h = 1.2, k = 8. Maximum height 8 m at t = 1.2 s, within the modelled flight interval.",
            verified_by="read-k-and-sign-a",
        ),
        item(
            cid="vf-compare-two-writings",
            title="Same curve, two writings",
            student_facing="Consider f(x) = 2(x + 3)^2 + 1 and g(x) = 2x^2 + 12x + 19. What should be the same about their graphs, and what is easier to read from f than from g?",
            family_id="equivalent-forms",
            bloom="understand",
            bloom_secondary="apply",
            rationale="Connect expansion to readable vertex features.",
            knowledge="conceptual",
            task_family="compare",
            codes=["A2.7", "A2.10"],
            processes=["expand-and-verify"],
            solution="They are the same function: expanding f gives g. Graphs coincide. From f you read vertex (−3, 1), axis x = −3, and a minimum (a > 0). From g those facts are not visible by inspection.",
            verified_by="expand-a-h-k: a=2, h=-3, k=1 → (2, 12, 19)",
        ),
        item(
            cid="vf-predict-h-only",
            title="Predict a horizontal shift from h",
            student_facing="Start from f(x) = 2(x + 3)^2 + 1. If only h changes so the vertex sits at x = 2, what happens to the graph, and what is the new equation? Write that before you move a graph.",
            family_id="predict-parameter-change",
            bloom="apply",
            rationale="Predict one-parameter change, then check.",
            knowledge="conceptual",
            task_family="investigate",
            processes=["predict-parameter-change"],
            rin=["symbolic"],
            rout=["symbolic", "graph"],
            solution="New vertex x is 2, so h = 2. a = 2 and k = 1 stay. New equation f(x) = 2(x − 2)^2 + 1. The graph translates horizontally; vertex moves from (−3, 1) to (2, 1).",
            verified_by="replace-h-only",
        ),
        item(
            cid="vf-fresh-read",
            title="Read a new downward-opening vertex form",
            student_facing="Consider f(x) = −0.5(x − 2)^2 + 4. Name the vertex, the axis of symmetry, and whether the vertex is a maximum or a minimum. If you expanded it to standard form, would the curve move?",
            family_id="read-vertex-features",
            bloom="apply",
            rationale="Independent retrieval of inspection plus A2.7 awareness.",
            knowledge="conceptual",
            task_family="interpret",
            role="transfer",
            codes=["A2.10", "A2.7"],
            solution="Vertex (2, 4). Axis x = 2. a = −0.5 < 0: maximum. Expansion gives −0.5x^2 + 2x + 2; the graph does not move.",
            verified_by="match-to-vertex-form and expand-a-h-k: a=-0.5, h=2, k=4 → (-0.5, 2, 2)",
        ),
        item(
            cid="vf-unique-opening-and-point",
            title="Vertex, opening, and a point: is a unique?",
            student_facing="A parabola has vertex (2, 5), opens downward, and passes through (0, 1). Write its vertex-form equation. Could a different negative a still work?",
            family_id="vertex-and-point-to-function",
            bloom="create",
            rationale="Construct and test uniqueness when opening is constrained.",
            knowledge="procedural",
            task_family="construct",
            recipe="constraint-construction",
            difficulty="extension",
            rin=["coordinates"],
            rout=["symbolic"],
            solution="h = 2, k = 5, a < 0. Through (0, 1): a(0 − 2)^2 + 5 = 1 → 4a = −4 → a = −1. f(x) = −(x − 2)^2 + 5. No other a works: the extra point fixes a.",
            verified_by="substitute-second-point",
        ),
        item(
            cid="vf-excluded-nelson-bank",
            title="Nelson bank items (internal only)",
            student_facing="[not for student export — Nelson Functions 11 local-bank stems]",
            family_id="internal-restricted",
            bloom="apply",
            rationale="Placeholder family for excluded commercial stems.",
            knowledge="factual",
            task_family="compute",
            solution="",
            verified_by="",
            status="excluded",
            origin="internal-source",
            source_id="nelson-mcf3m-4-1",
            export=False,
            exclusion="Restricted pending reuse rights. Do not export source wording or crops. Use original prompts in accepted records instead.",
        ),
        item(
            cid="vf-excluded-mathnet-0gz2",
            title="MathNet 0gz2 olympiad stem",
            student_facing="[not for student export — contest packing]",
            family_id="internal-restricted",
            bloom="create",
            rationale="Contest item is out of lesson difficulty and licence gate.",
            knowledge="procedural",
            task_family="construct",
            solution="",
            verified_by="",
            status="excluded",
            origin="internal-source",
            source_id="mathnet-0gz2",
            export=False,
            exclusion="Olympiad difficulty; contest stem is not classroom copy. Convenience key unverified.",
        ),
        item(
            cid="vf-excluded-regression",
            title="Historical data-fitting (out of scope)",
            student_facing="[not for this lesson — regression and full model-from-data stay in later lessons]",
            family_id="data-modelling",
            bloom="evaluate",
            rationale="Documented exception: do not manufacture A3.3/regression padding in L1.",
            knowledge="conceptual",
            task_family="model",
            recipe="model-critique",
            status="excluded",
            origin="internal-source",
            source_id="nelson-mcf3m-4-1-q15",
            export=False,
            exclusion="Q15-style data fitting is labelled historical and out of this lesson’s approved scope. Recorded as a coverage exception, not a quota filler.",
        ),
    ]
    return {
        "schema_version": "question-pool.v1",
        "lesson_id": LESSON,
        "course_code": "MCF3M",
        "scope": SCOPE,
        "coverage": {
            "families": [
                {"id": "read-vertex-features", "needed": True, "notes": "Inspect (h, k), axis, max/min from a."},
                {"id": "equivalent-forms", "needed": True, "notes": "Expand vertex form; sampled tables corroborate only."},
                {"id": "form-affordances", "needed": True, "notes": "Choose vertex form for vertex/axis/max without producing other forms."},
                {"id": "zeros-from-vertex-form", "needed": True, "notes": "Inverse operations only; no quadratic formula."},
                {"id": "vertex-and-point-to-function", "needed": True, "notes": "Construct a from vertex + point; uniqueness."},
                {"id": "error-diagnosis", "needed": True, "notes": "h-sign, max-from-k, expand errors."},
                {"id": "method-choice", "needed": True, "notes": "Prove-for-all-x vs graph corroboration."},
                {"id": "claim-testing", "needed": True, "notes": "Axis claim; table-as-proof."},
                {"id": "constraint-construction", "needed": True, "notes": "Same vertex different a; uniqueness."},
                {"id": "model-critique", "needed": True, "notes": "Meaningful domain of a simple height model; not Nelson bungee."},
                {"id": "representation-bridge", "needed": True, "notes": "Graph/table features ↔ vertex form."},
                {"id": "maximum-from-representations", "needed": True, "notes": "Read max from vertex form in a modelled interval."},
                {"id": "predict-parameter-change", "needed": True, "notes": "Change only h."},
                {
                    "id": "data-modelling",
                    "needed": False,
                    "notes": "Regression / historical cigarette table.",
                    "exception": "Out of approved L1 scope; do not pad.",
                },
            ],
            "gaps": [
                "error-diagnosis",
                "method-choice",
                "claim-testing",
                "constraint-construction",
                "model-critique",
                "zeros-from-vertex-form",
                "vertex-and-point-to-function",
                "representation-bridge",
            ],
            "counting_rule": "Count distinct reasoning families separately from numeric or surface-context variants (variant_of).",
            "target_accepted": [24, 36],
        },
        "candidates": candidates,
    }


def main() -> int:
    """Validate, write JSON, rebuild FTS."""
    doc = build()
    validate_pool(doc)
    dups = near_duplicates(doc)
    if dups:
        raise SystemExit(f"near-duplicates: {dups}")
    dest = pool_path("MCF3M", LESSON)
    dump_json(dest, doc)
    root = Path(__file__).resolve().parents[1]
    brief = {
        "lesson_id": LESSON,
        "scope": SCOPE,
        **coverage_report(doc),
        "gaps_filled": doc["coverage"]["gaps"],
        "excluded": [c["id"] for c in doc["candidates"] if c["status"] != "accepted"],
    }
    dump_json(root / "lessons" / "MCF3M" / "M4-L1-vertex-form" / "coverage-brief.json", brief)
    rebuild_index()
    print(json_brief(brief, dest))
    return 0


def json_brief(brief: dict, dest: Path) -> str:
    """Format a one-line write confirmation."""
    import json

    return json.dumps({"wrote": str(dest), **brief}, indent=2)


if __name__ == "__main__":
    raise SystemExit(main())
